// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkn0-I3RZ_h-Kxx2uwbnMRhakgBJ5GViY',
    appId: '1:753266176603:web:3e3e6c389137811b16857e',
    messagingSenderId: '753266176603',
    projectId: 'fir-project-pkl',
    authDomain: 'fir-project-pkl.firebaseapp.com',
    storageBucket: 'fir-project-pkl.firebasestorage.app',
    measurementId: 'G-TYZX5ZZJ5Z',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkn0-I3RZ_h-Kxx2uwbnMRhakgBJ5GViY',
    appId: '1:753266176603:web:94649c3c29b0616f16857e',
    messagingSenderId: '753266176603',
    projectId: 'fir-project-pkl',
    authDomain: 'fir-project-pkl.firebaseapp.com',
    storageBucket: 'fir-project-pkl.firebasestorage.app',
    measurementId: 'G-W90Q0CN8Z5',
  );
}
